### ISSUE TITLE
new Gremlin todo 

### ISSUE THREAD

**Issue by rene-dev** [LinuxCNC/linuxcnc#954]
This issue tracks the progress of the new gremlin in https://github.com/LinuxCNC/linuxcnc/pull/943
- [ ] Tool Preview, lathe and milling
- [ ] Backplot
- [ ] extends with dimensions, and min/max values
- [ ] fix event system, adjustable mouse behavior, preview buttons
- [ ] use same opengl codebase in all UIs(axis, QT)
- [ ] arbitrary object rendering, like vismach
- [ ] offsets (g54,...)
- [ ] coordinate system rotations
- [ ] selection of gcode line <-> gcode view
- [ ] Grid view

**Comment by rene-dev** [comment]
Thanks to stackoverflow, we managed to use legacy opengl in gtk3.
